version: '3.8'
services:
  nginx:
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './server/nginx/sites-available:/etc/nginx/sites-available'
      - './server/nginx/sites-enabled:/etc/nginx/sites-enabled'
      - './server/nginx/conf.d:/etc/nginx/conf.d'
      - './docker-entrypoint.d/init.sh:/docker-entrypoint.d/init.sh'
      - './server/nginx/ssl:/etc/nginx/ssl'
      # - './server/nginx:/etc/nginx/'

